name: 03-BUILD WITH CACHE AND UPLOAD/DOWNLOAD ARTIFACTS
run-name: BUILD WITH CACHE AND UPLOAD/DOWNLOAD ARTIFACTS

on:
  workflow_dispatch:
  push:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}' >> $GITHUB_STEP_SUMMARY

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != true
        run: npm install

      - name: Display Checkout Directory
        run: ls -la

  build:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Checkout Repo
        run: ls -la

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != true
        run: npm install

      - name: Build Project
        run: npm run build

  test-and-upload-artefact:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Checkout Repo
        working-directory: app/
        run: ls -la >> $GITHUB_STEP_SUMMARY

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Install Dependencies
        working-directory: app
        if: steps.cache-dependencies.outputs.cache-hit != true
        run: npm install

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'

      - name: Run Tests
        id: test
        working-directory: app
        run: npx jest

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'

      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: app/coverage
          retention-days: 10

  download-artefact:
    runs-on: ubuntu-latest
    needs: [test-and-upload-artefact]
    steps:
      - name: Download Artefact
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: code-coverage-report

      - run: ls -a
        working-directory: code-coverage-report

  delete-artefact:
    runs-on: ubuntu-latest
    needs: [download-artefact]
    steps:
        - name: Delete Artefact
          uses: geekyeggo/delete-artifact@v2
          with:
            name: code-coverage

  axios:
    runs-on: ubuntu-latest
    needs: [download-artefact]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Checkout Repo
        working-directory: app/
        run: ls -la >> $GITHUB_STEP_SUMMARY

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Install Dependencies
        working-directory: app
        if: steps.cache-dependencies.outputs.cache-hit != true
        run: npm install

      - name: Install Axios
        run: npm install axios

      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)
