name: 05-RANDOM NUMBER GENERATOR WITH CONDITIONAL JOB AND STEP EXECUTION
run-name: RANDOM NUMBER GENERATOR WITH CONDITIONAL JOB AND STEP EXECUTION

on:
    workflow_dispatch:
    push:

jobs:
    random-number-generator:
        runs-on: ubuntu-latest
        outputs:
            random-number: ${{ steps.generate-random-number.outputs.random-number }}
            is-even: ${{ steps.is-even.outputs.is-even }}

        steps:
            - name: Generate Random Number
              id: generate-number
              run: |
                echo "Generating Random Number..."
                random_number=$(shuf -i 1-100 -n 1)
                echo "Generated Random Number: $random_number"
                echo "random-number=$random_number" >> "$GITHUB_OUTPUT"
                echo "### Generated Random Number: $random_number" >> "$GITHUB_STEP_SUMMARY"

            - name: Check If Random Number Is Even
              id: is-even
              run: |
                echo "Checking If Random Number Is Even..."
                random_number=${{ steps.generate-number.outputs.random-number }}
                is_even=$((random_number % 2 == 0))
                echo "Is Random Number Even? $is_even"
                echo "is-even=$is_even" >> "$GITHUB_OUTPUT"
                echo "### Is Random Number Even? $is_even" >> "$GITHUB_STEP_SUMMARY"


