name: 05-Conditional-Jobs-Steps-RandNumGen
run-name: Conditional Jobs and Steps with Random Number Generation

on:
    workflow_dispatch:

jobs:
    random-number-generator:
        runs-on: ubuntu-latest
        steps:
            - name: Generate Random Number
              id: random-number-generator
              run: echo "::set-output name=randNum::$(shuf -i 1-100 -n 1)"
            - name: Display Random Number
              run: echo "Random Number: ${{ steps.randNumGen.outputs.randNum }}"