name: 06-SHOW STATUS CHECK
run-name: SHOW STATUS CHECK

on:
    workflow_dispatch:
    push:
    
jobs:
    job-1:
      runs-on: self-hosted
      timeout-minutes: 1
      steps:
        - name: Step 1
          run: | 
            sleep 90
            echo "Displaying Status Check..."
            echo "### Status Check: ${{ job.status }}" >> "$GITHUB_STEP_SUMMARY"
          # timeout-minutes: 1

        - name: Step 2
          id: step-2
          continue-on-error: true
          run: | 
            exit 1

        - name: Runs on step 2 Failure
          if: failure() && steps.step-2.conclusion == 'failure'
          run: | 
            echo 'Step 2 has failed'
            echo "Displaying Status Check..."
            echo "### Status Check: ${{ job.status }}" >> "$GITHUB_STEP_SUMMARY"

        - name: Runs on Failure
          if: failure()
          run: echo 'Failure'

        - name: Runs on Success
          # This is not needed (DEFAULT BEAHAVIOUR)
          if: success()
          run: echo 'Runs on Success'

        - name: Always Runs
          # if: success() || failure()
          if: always()
          run: echo 'Always Runs'

        - name: Runs When Cancelled
          if: cancelled()
          run: echo 'Runs on Cancelled'

    job-2:
      runs-on: ubuntu-latest
      needs: job-1
      if: failure()
      steps:
        - run: echo 'Job 2'
