name: Node.js CI - WITH NO CACHE

# Cache mekanizmasi olmaksizin calistirilan build isleminde, her seferinde node_modules klasoru silinir
# ve npm ci komutu ile node_modules klasoru yeniden olusturulur. Dolayisiyla, her seferinde tum paketlerin
# indirilmesi gerekmektedir. Bu durum, build isleminin daha uzun surmesine neden olur.

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: |
          cd app
          npm run build --if-present
