name: Node.js CI - WITH NO CACHE

# Cache mekanizmasi olmaksizin calistirilan build isleminde, her seferinde node_modules klasoru silinir
# ve npm ci komutu ile node_modules klasoru yeniden olusturulur. Dolayisiyla, her seferinde tum paketlerin
# indirilmesi gerekmektedir. Bu durum, build isleminin daha uzun surmesine neden olur.

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Show directory
        run: ls -la

      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install Dependencies
        run: | 
          cd app
          npm ci

      - name: Run Tests
        run: cd app && npm test

      - name: Build
        run: cd app && npm run build --if-present
