name: Node.js CI - WITH NO CACHE
run-name: Node.js CI - BUILD WITH NO CACHE

# Cache mekanizmasi olmaksizin calistirilan build isleminde, her seferinde node_modules klasoru silinir
# ve npm ci komutu ile node_modules klasoru yeniden olusturulur. Dolayisiyla, her seferinde tum paketlerin
# indirilmesi gerekmektedir. Bu durum, build isleminin daha uzun surmesine neden olur.

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Node version
        type: choice
        options:
          - 14.x
          - 18.x
          - 20.x
          - 21.x
          - latest
        default: latest

  push:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        working-directory: app
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      
      - name: Install Depenencies
        run: npm ci

      - name: Building
        working-directory: app/node_modules
        run: npm run build
