name: Node.js CI - WITH CACHE

# Cache mekanizmasi olmaksizin calistirilan build isleminde, her seferinde node_modules klasoru silinir
# ve npm ci komutu ile node_modules klasoru yeniden olusturulur. Dolayisiyla, her seferinde tum paketlerin
# indirilmesi gerekmektedir. Bu durum, build isleminin daha uzun surmesine neden olur.

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore from Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"

      - name: Run Build
        run: |
          npm ci

      - name: Npm Build
        run: |
          cd app
          npm run build --if-present

      - name: Save Cache Npm
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
