name: Caching and Artifacts
run-name: Node.js CI - BUILD WITH CACHE AND ARTIFACTS

on: [workflow_dispatch, push]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Checkout Repo
        run: ls -la

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'

      - name: Install Dependencies
        working-directory: app
        run: npm install

      - name: Run Tests
        working-directory: app
        run: npm test

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: coverage
          retention-days: 10

      - name: Download Code Coverage
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: code-coverage-report

      - run: ls -a

      - run: ls -a
        working-directory: code-coverage-report

      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)
